### ISSUE TITLE
Expose API Error in Exceptions

### ISSUE THREAD

**Issue by CovetingEpiphany2152** [YukiGasai/obsidian-google-calendar#90]
I've been toying with the plugin's API and it's been working great. However, I'm running into an issue.

The plugin API fails with the same failure regardless of the reason. For example, if I were to try to get/delete an event that's already deleted, Google Calendar API will return this:
```json
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "Not Found"
   }
  ],
  "code": 404,
  "message": "Not Found"
 }
}
```

But the `getEvent()` API throws an error without telling me why:
```
plugin:google-calendar:26 Uncaught TypeError: Cannot set properties of undefined (setting 'parent')
    at eval (plugin:google-calendar:25:82027)
    at Generator.next (<anonymous>)
    at a (plugin:google-calendar:6:1196)
eval @ plugin:google-calendar:25
a @ plugin:google-calendar:6
```

For the `deleteEvent()` API, it returns `false` without any indication of what was wrong.

It would be great if this plugin sanitizes the response from Google API, and if it is unexpected, throws an error with the response or its error code. Hopefully, that helps both this plugin and other plugins to handle errors better.

**Comment by YukiGasai** [comment]
Hi,
in the settings is a option Debug Mode to enable more detailed Network errors in the Networking tab inside the dev console. 
Does this fit your request?

**Comment by YukiGasai** [comment]
Ok I see. I was not really expecting anyone to use this API inside another plugin. That's why all errors were intended to be resolved internally. So you would like the API endpoint to throw an exception that contains the original response from the Google API?

**Comment by CovetingEpiphany2152** [comment]
Give  how useful this plugin is, I'm sure there would be use cases on integration with other plugin 😉
Yes, I would love it if it's possible expose the original response from google api!

**Comment by YukiGasai** [comment]
Hi @CovetingEpiphany2152,
I implemented a [GoogleApiError](https://github.com/YukiGasai/obsidian-google-calendar/blob/cde8cf66d7de3c256ae3eb621132899cae8364b0/src/googleApi/GoogleApiError.ts#L1-L22). It should be thrown when using the API function. 
I am really new to working with exceptions and hope it doesn't break everything 😓.
Some errors may still be handled by the plugin, If you find any problems, just report them here.

**Comment by CovetingEpiphany2152** [comment]
Thanks @YukiGasai ! I did some simple testing like getting/deleting events that don't exist, and it seems to work well.

However, it looks like when there is no response from Gcal API, the previous error is still seen. Here's an example of me trying to get an event when I disconnected my device from the internet. The gcal event and calendar ids are removed for privacy.

```
event = await app.plugins.plugins['google-calendar'].api.getEvent('REMOVED', 'REMOVED').catch((e)=>console.log(e))
plugin:google-calendar:25 New Request GET:https://www.googleapis.com/calendar/v3/calendars/REMOVED
plugin:google-calendar:25 {body: null, headers: {…}}
plugin:google-calendar:25          GET https://www.googleapis.com/calendar/v3/calendars/REMOVED net::ERR_NAME_NOT_RESOLVED
eval @ plugin:google-calendar:25
a @ plugin:google-calendar:6
Promise.then (async)
c @ plugin:google-calendar:6
eval @ plugin:google-calendar:6
G @ plugin:google-calendar:6
In @ plugin:google-calendar:25
eval @ plugin:google-calendar:25
eval @ plugin:google-calendar:6
G @ plugin:google-calendar:6
Kc @ plugin:google-calendar:25
getEvent @ plugin:google-calendar:48
(anonymous) @ VM335:1
plugin:google-calendar:25 undefined
VM335:1 TypeError: Cannot read properties of undefined (reading 'status')
    at eval (plugin:google-calendar:25:34819)
    at Generator.throw (<anonymous>)
    at l (plugin:google-calendar:6:1240)
```

The current error is due to accessing 'status' from an undefined. Which does not really tell us what went wrong.
Would like make more sense to throw an error that no response is received?

**Comment by CovetingEpiphany2152** [comment]
I just retested this in 1.9.10 and it seems to be fixed.

**Comment by CovetingEpiphany2152** [comment]
Oh wait, this seems to be a problem still for the deleteEvent API. It still returns true if success, and false if failed. But the user would not know why it failed.
